# Nifty 200 constituent symbols in TrueData F&O format (append -I for continuous futures)
# Source: NSE Nifty 200 index constituents
# Update this list periodically as index composition changes

NIFTY200_SYMBOLS = [

    # Nifty 50
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "HCLTECH",
    "SUNPHARMA", "TITAN", "BAJFINANCE", "ULTRACEMCO", "WIPRO",
    "NESTLEIND", "POWERGRID", "NTPC", "TECHM", "TATAMOTORS",
    "INDUSINDBK", "ONGC", "TATASTEEL", "COALINDIA", "BAJAJFINSV",
    "ADANIENT", "ADANIPORTS", "JSWSTEEL", "HINDALCO", "DRREDDY",
    "CIPLA", "DIVISLAB", "GRASIM", "APOLLOHOSP", "EICHERMOT",
    "BRITANNIA", "TATACONSUM", "BPCL", "HEROMOTOCO", "SBILIFE",
    "HDFCLIFE", "M&M", "UPL", "SHRIRAMFIN", "BAJAJ-AUTO",

    # Nifty Next 50
    "VEDL", "SIEMENS", "HAL", "GODREJCP", "PIDILITIND",
    "DABUR", "MARICO", "BERGEPAINT", "MCDOWELL-N", "COLPAL",
    "AMBUJACEM", "ACC", "INDIGO", "BANKBARODA", "PNB",
    "CANBK", "UNIONBANK", "IDBI", "FEDERALBNK", "IDFCFIRSTB",
    "MUTHOOTFIN", "CHOLAFIN", "RECLTD", "PFC", "IRFC",
    "DLF", "GODREJPROP", "PRESTIGE", "OBEROIRLTY", "PHOENIXLTD",
    "ZOMATO", "NYKAA", "POLICYBZR", "PAYTM", "DELHIVERY",
    "TRENT", "ABFRL", "PAGEIND", "RAJESHEXPO", "MPHASIS",
    "LTIM", "PERSISTENT", "COFORGE", "KPITTECH", "TANLA",
    "AUROPHARMA", "TORNTPHARM", "ALKEM", "LALPATHLAB", "METROPOLIS",

    # Nifty Midcap 100 (partial — major ones)
    "IPCALAB", "GLENMARK", "NATCOPHARM", "GRANULES", "LAURUSLABS",
    "SYNGENE", "FORTIS", "MAXHEALTH", "ASTER", "YATHARTH",
    "ASHOKLEY", "MOTHERSON", "BOSCHLTD", "BALKRISIND", "APOLLOTYRE",
    "CEATLTD", "MRF", "TVSMOTOR", "BAJAJHLDNG", "SCHAEFFLER",
    "SKFINDIA", "TIMKEN", "GRINDWELL", "CUMMINSIND", "THERMAX",
    "ABB", "BHEL", "BEL", "COCHINSHIP", "MAZAGON",
    "KFINTECH", "CAMSSEBI", "CDSL", "BSE", "MCX",
    "IIFL", "ANGELONE", "5PAISA", "MOTILALOFS", "ISEC",
    "SUNTV", "ZEEL", "PVRINOX", "INOXWIND", "SUZLON",
    "ADANIGREEN", "ADANITRANS", "ADANIPOWER", "TATAPOWER", "CESC",
    "TORNTPOWER", "NHPC", "SJVN", "IREDA", "GREENKO",
    "WHIRLPOOL", "VOLTAS", "BLUESTAR", "HAVELLS", "POLYCAB",
    "KEI", "FINOLEX", "GMRAIRPORT", "CONCOR", "IRCTC",
    "RAILTEL", "RVNL", "TITAGARH", "TEXRAIL", "GPPL",
    "ASTRAL", "SUPREMEIND", "FINOLEX", "PRINCEPIPE", "VGUARD",
    "DIXON", "AMBER", "KAYNES", "SYRMA", "AVALON",
    "HAPPSTMNDS", "SONATSOFTW", "MASTEK", "NIITLTD", "ZENSAR",
    "LICI", "GICRE", "NIACL", "STARHEALTH", "ICICIGI",
    "HDFCAMC", "ABCAPITAL", "MANAPPURAM", "SUNDARMFIN", "BAJAJHFL",
    "AARTIIND", "DEEPAKNTR", "NAVINFLUOR", "SRF", "PIIND",
    "COROMANDEL", "CHAMBLFERT", "GNFC", "GUJGASLTD", "IGL",
    "MGL", "GAIL", "OIL", "MRPL", "HPCL",
]